const phases = [
  'angel',
  'series a',
  'series b',
  'seed',
  'series c',
  'series d',
  'series unknown',
  'debt financing',
  'series e',
  'private equity',
  'series f',
  'pre seed',
  'undisclosed',
  'grant',
  'post ipo equity',
  'convertible note',
  'post ipo debt',
  'non equity assistance',
  'corporate round',
  'series i',
  'series g',
  'secondary market',
  'initial coin offering',
  'series h',
  'product crowdfunding',
  'equity crowdfunding',
  'post ipo secondary',
  'series j'
].sort();

const categories = [
  'Financial Services',
  'Lending and Investments',
  'Payments',
  'Artificial Intelligence',
  'Data and Analytics',
  'Platforms',
  'Privacy and Security'
].sort();

const countries = [
  'United States',
  'Hong Kong',
  'Ireland',
  'Luxembourg',
  'Switzerland',
  'United Kingdom',
  'Spain',
  'Israel',
  'Canada',
  'Russian Federation',
  'Germany',
  'Australia',
  'France',
  'Finland',
  'Sweden',
  'India',
  'Korea, Republic of',
  'Netherlands',
  'Belgium',
  'Singapore',
  'Japan',
  'United Arab Emirates',
  'Denmark',
  'Venezuela, Bolivarian Republic of',
  'China',
  'Philippines',
  'Indonesia',
  'South Africa',
  'Brazil',
  'Czechia',
  'New Zealand',
  'Poland',
  'Thailand',
  'Argentina',
  'Estonia',
  'Austria',
  'Turkey',
  'Mauritius',
  'Malta',
  'Kuwait',
  'Viet Nam',
  'Italy',
  'Romania',
  'Egypt',
  'Qatar',
  'Cyprus',
  'Greenland',
  'Trinidad and Tobago',
  'Malaysia',
  'Norway',
  'Portugal',
  'Taiwan, Province of China',
  'Bulgaria',
  'Pakistan',
  'Lebanon',
  'Chile',
  'Ukraine',
  'Slovenia',
  'Armenia',
  'Mexico',
  'Hungary',
  'Nicaragua',
  'Isle of Man',
  'Gibraltar',
  'Tunisia',
  'Bahrain',
  'Barbados',
  'Costa Rica',
  'Greece',
  'Iceland',
  'Bermuda',
  'Peru',
  'Nigeria',
  'Latvia',
  'Kenya',
  'Saudi Arabia',
  'Bangladesh',
  'Uruguay',
  'Ethiopia',
  'Dominican Republic',
  'Jordan',
  'Cayman Islands',
  'Lithuania',
  'Croatia',
  'North Macedonia',
  'Sri Lanka',
  'Bosnia and Herzegovina',
  "C\xc3\xb4te d'Ivoire",
  'Morocco',
  'Liechtenstein',
  'Afghanistan',
  'Bolivia, Plurinational State of',
  'Serbia',
  'Azerbaijan',
  'Colombia',
  'Belarus',
  'Kyrgyzstan',
  'Iran, Islamic Republic of',
  'Ecuador',
  'Antigua and Barbuda',
  'Kazakhstan',
  'Albania',
  'Uzbekistan',
  'Guernsey',
  'Ghana',
  'Jersey',
  'Iraq',
  'Uganda',
  'Cameroon',
  'Panama',
  'El Salvador',
  'Algeria',
  'Slovakia',
  'Georgia',
  'Cuba',
  'Moldova, Republic of',
  'Nepal',
  'Jamaica',
  'Sierra Leone',
  'Puerto Rico',
  'Norfolk Island',
  'Martinique',
  'Saint Martin (French part)',
  'Andorra',
  'Senegal',
  'Bahamas',
  'Maldives',
  'Paraguay',
  'Yemen',
  'Belize',
  'Haiti',
  'Dominica',
  'Montenegro',
  'Brunei Darussalam',
  "Lao People's Democratic Republic",
  'Seychelles',
  'Angola',
  'Gambia',
  'Guyana',
  'Syrian Arab Republic',
  'Somalia',
  'Tanzania, United Republic of',
  'Zimbabwe',
  'Rwanda',
  'Mongolia',
  'Benin',
  'Saint Kitts and Nevis',
  'Macao',
  'Palestine, State of',
  'Guatemala',
  'Botswana',
  'Honduras',
  'Oman',
  'Namibia',
  'Cambodia',
  'Zambia',
  'Myanmar',
  'Madagascar',
  'Togo',
  'Saint Lucia',
  'Sudan',
  'Faroe Islands',
  'Mozambique',
  'Aruba',
  'Tajikistan',
  'Guam',
  'Comoros',
  'Libya',
  'Burkina Faso',
  'Malawi',
  'Suriname',
  'French Polynesia',
  'Turkmenistan',
  'Fiji',
  'American Samoa',
  'Northern Mariana Islands',
  'Grenada',
  'Lesotho',
  'Liberia',
  "Korea, Democratic People's Republic of",
  'Congo, The Democratic Republic of the',
  'Bhutan',
  'Congo',
  'Central African Republic',
  'Montserrat',
  'New Caledonia',
  'Mali',
  'Saint Barth\xc3\xa9lemy',
  'Marshall Islands',
  'French Guiana',
  'Guinea',
  'Eswatini',
  'Papua New Guinea',
  'Djibouti',
  '\xc3\x85land Islands',
  'Chad',
  'Turks and Caicos Islands',
  'R\xc3\xa9union',
  'Gabon',
  'Mauritania',
  'Niger',
  'Cabo Verde',
  'Anguilla',
  'Falkland Islands (Malvinas)',
  'Guadeloupe',
  'Burundi',
  'British Indian Ocean Territory',
  'Timor-Leste',
  'Equatorial Guinea',
  'San Marino',
  'Solomon Islands',
  'Cook Islands',
  'unknown'
].sort();

const sizes = [
  '1-10',
  '11-50',
  '51-100',
  '101-250',
  '251-500',
  '501-1000',
  '1001-5000',
  '5001-10000',
  '10000+',
  'unknown'
];

export { phases, categories, sizes, countries };
